### ISSUE TITLE
Minecraft 1.17 doesn't start

### ISSUE THREAD

**Issue by ErikPelli** [guihkx/com.teamshiginima.ShiginimaLauncher#5]
Minecraft 1.17 doesn't start because java 16 is required, please change the openjdk version in the flatpak.

**Comment by guihkx** [comment]
Thanks for the heads up! :)

I just released a new version with an updated JRE, please give it a go. :)

**Comment by ErikPelli** [comment]
Everything works, I'm happy to have been of help.
