### ISSUE TITLE
Minecraft 1.12.2 crashes on start

### ISSUE THREAD

**Issue by mar4ello6** [guihkx/com.teamshiginima.ShiginimaLauncher#7]
Here's log:
`---- Minecraft Crash Report ----
// Sorry :(

Time: 2021-07-03 16:41
Description: Initializing game

java.lang.ExceptionInInitializerError
	at bib.av(SourceFile:661)
	at bib.aq(SourceFile:456)
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:951)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 4 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at bib.av(SourceFile:661)
	at bib.aq(SourceFile:456)

-- Initialization --
Details:
Stacktrace:
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.4.0-77-generic
	Java Version: 16.0.1, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	Memory: 77138432 bytes (73 MB) / 162529280 bytes (155 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 3 total; -Xmx1G -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: Cannot invoke "cfa.c()" because the return value of "bib.b(bib)" is null
	Profiler Position: N/A (disabled)
	CPU: <unknown>`

**Comment by guihkx** [comment]
What is your distribution and GPU? Have you tried running `flatpak update` to see if there's a driver update?

**Comment by mar4ello6** [comment]
I tried `flatpak update`, it outputs `Nothing to do`.
I have Linux Mint 20.1, my GPU is Nvidia Geforce MX150
Also, I just tried to run Minecraft 1.17 and it started, but Minecraft 1.12.2 still crashes.

**Comment by guihkx** [comment]
Thanks for providing more info, I was able to reproduce the crash and found a fix. Will be pushing a new release soon! :)

![2021-07-03_12 43 24](https://user-images.githubusercontent.com/626206/124359709-7bc9db00-dbfc-11eb-9dc4-c6a23c8af7ef.png)
