### ISSUE TITLE
so, the official website is down...

### ISSUE THREAD

**Issue by Alistair1231** [guihkx/com.teamshiginima.ShiginimaLauncher#8]
The official website is down and I fear the project may be dead.
Is it possible to build the project from source under windows (or under linux for windows) with the help of your repository?

If not, could you make it possible?
I ask, since I see you are updating this project.
Kind regards

**Comment by guihkx** [comment]
>The official website is down

Yes, but you can still download the launcher from web.archive.org. And the launcher still works.

>Is it possible to build the project from source under windows

No, sorry. I don't have the source code.

>If not, could you make it possible?

Nope. This project merely packages the already compiled .jar file.
